arch: 'timesformer'
device_id: 1
patch_size: 16
out_dim: 65536
norm_last_layer: True
momentum_teacher: 0.9999
use_bn_in_head: False
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 5
clip_grad: 1.0
batch_size_per_gpu: 64
epochs: 
freeze_last_layer: 1
lr: 0.0005
warmup_epochs: 8
min_lr: 1.0e-6
optimizer: 'adamw'
global_crops_scale: (0.4, 1.)
local_crops_number: 8
local_crops_scale: (0.05, 0.4)
pretrained_rgb: None
output_dir: "./output"
seed: 0
num_workers: 10
eval_batch_size_per_gpu: 128
nb_knn: 5
temperature: 0.07
masked_im_modeling: True
epochstart: 0
use_parallel: True
mode: "GRAPH_MODE"
parallel_mode: "DATA_PARALLEL"
device_target: "Ascend"
max_call_depth: 10000
save_graphs: False
RAND_FR: True
NUM_ENSEMBLE_VIEWS: 1
NUM_SPATIAL_CROPS: 3
PATH_LABEL_SEPARATOR: " "
PATH_PREFIX: ""
TRAIN_CROP_SIZE: 224
DEFAULT_S: 0
TEST_CROP_SIZE: 256
LONG_CYCLE_SAMPLING_RATE: 0
SAMPLING_RATE: 32
ENABLE_MULTI_THREAD_DECODE: False
DECODING_BACKEND: 'pyav'
NUM_FRAMES: 8
TARGET_FPS: 30
NO_RGB_AUG: False
TWO_TOKEN: False
PATH_TO_DATA_DIR: "/home/ma-user/modelarts/user-job-dir/svt"
NUM_CLASSES: 400
ATTENTION_TYPE: "divided_space_time"
PRETRAINED_MODEL: " "
TRAIN_JITTER_SCALES_0: 256
TRAIN_JITTER_SCALES_1: 320
MULTIGRID_DEFAULT_S: 0
SHORT_CYCLE_FACTORS_0: 0.5
SHORT_CYCLE_FACTORS_1: 0.707
MEAN: [0.45, 0.45, 0.45]
STD: [0.225, 0.225, 0.225]
start_learning_rate: 5.0e-4
base_lr: 5.0e-4
end_learning_rate: 1.0e-6
#use_ckpt: "../outputcheckpoint/model-14_7323.ckpt"
use_ckpt: ""
accum_iter: 1
test_num_spatial_crops: 3

train_url: ""
output_path: "/cache/train"
save_dir: "/cache/train"
ckpt_path: '/cache/train/'
obs_output_path: " "


depth: 12
num_heads: 12
layer_decay: 2.0

save_ckpt_epochs: 10
opt: 'adamw'
beta: [ 0.9, 0.999 ]
weight_decay: 0.04
weight_decay_end: 0.1
eps: 1.0e-8
per_step_size: 0
gradients_mean: False
sink_mode: False
label_smoothing: 0.0
test: False
eval: False
prefix1: 'teacher'
prefix2: 'student'
batch_size: 4
repeat_aug: 1
use_dynamic_loss_scale: True
loss_scale: 1024
is_dynamic_loss_scale: True
clip_global_norm_value: 3.0
eps: 1.0e-8
accumulation_step: 1

